#!name=AQI-US
#!desc=将 iOS 系统原生 天气 App 的空气质量标准改为 AQI-US

[Script]
AQI-US-v1 = type=http-response, pattern=https://weather-data.apple.com/v1/weather/[\w-]+/[0-9]+\.[0-9]+/[0-9]+\.[0-9]+\?, requires-body=true, script-path=http://ios-weather-aqi-standard.vercel.app/script.js?version=v1&token=b090ce1d97ddb40645bf60eeb9b5c585ee5b511c
AQI-US-v2 = type=http-response, pattern=https://weather-data.apple.com/v2/weather/[\w-]+/[0-9]+\.[0-9]+/[0-9]+\.[0-9]+\?, requires-body=true, script-path=http://ios-weather-aqi-standard.vercel.app/script.js?version=v2&token=b090ce1d97ddb40645bf60eeb9b5c585ee5b511c

[MITM]
hostname = %INSERT% weather-data.apple.com