#!name=Weather_AQI_US 
#!desc=Weather_AQI修改为US标准

[Script]
iOS14美标空气质量 = type=http-response,pattern=https://weather-data.apple.com/v1/weather/[\w-]+/-?[0-9]+\.[0-9]+/-?[0-9]+\.[0-9]+\?,requires-body=true,script-path=https://github.com/zhihenglu/SurgeModule/raw/master/Script/iOS14_Weather_AQI_US.js
iOS15美标空气质量 = type=http-response,pattern=https://weather-data.apple.com/v2/weather/[\w-]+/-?[0-9]+\.[0-9]+/-?[0-9]+\.[0-9]+\?,requires-body=true,script-path=https://github.com/zhihenglu/SurgeModule/raw/master/Script/iOS15_Weather_AQI_US.js
[MITM]
hostname = %APPEND% hostname = weather-data.apple.com