#!name=Get cookie
#!desc=该模块适用于定时签到脚本的Cookie获取. 
#!system=ios

[Script]

小米运动获取Token = type=http-response,pattern=^https:\/\/account\.huami\.com\/v2\/client\/login, requires-body=1, max-size=0, script-path=https://github.com/zhihenglu/SurgeModule/raw/master/Script/xmSports.js

彩云天气 = type=http-request,pattern=https://((weather-data.apple)|(api.weather)).com,script-path=https://raw.githubusercontent.com/Peng-YM/QuanX/master/Tasks/caiyun.js,script-update-interval=0

获取京东Cookie = type=http-request,requires-body=1,pattern=^https:\/\/(api\.m|me-api|ms\.jr)\.jd\.com\/(client\.action\?functionId=signBean|user_new\/info\/GetJDUserInfoUnion\?|gw\/generic\/hy\/h5\/m\/appSign\?),script-path=https://raw.githubusercontent.com/NobyDa/Script/master/JD-DailyBonus/JD_DailyBonus.js

[MITM]
hostname = %APPEND% account.huami.com,weather-data.apple.com,api.weather.com,ms.jr.jd.com, me-api.jd.com, api.m.jd.com

