#!name=Get cookie
#!desc=该模块适用于定时签到脚本的Cookie获取. 
#!system=ios

[Script]

# 京东
# 浏览器登录 https://bean.m.jd.com 点击签到并且出现签到日历
JD_DailyBonus.js = type=http-request,pattern=https:\/\/api\.m\.jd\.com\/client\.action.*functionId=signBean,script-path=https://raw.githubusercontent.com/NobyDa/Script/master/JD-DailyBonus/JD_DailyBonus.js

# 中国电信
http-request ^https:\/\/wapside.189.cn:9001\/api\/home\/sign script-path=https://raw.githubusercontent.com/chavyleung/scripts/master/10000/10000.cookie.js, requires-body=true

# 腾讯视频签到 手机浏览器访问: https://film.qq.com/随便选 1 部电影观看
videoqq.cookie.js = script-path=https://raw.githubusercontent.com/chavyleung/scripts/master/videoqq/videoqq.cookie.js,type=http-request,pattern=^https:\/\/access.video.qq.com\/user\/auth_refresh

# 爱奇艺获取
iQIYI.Cookie.js= type=http-request,pattern=^https?:\/\/iface(\d)?\.iqiyi\.com\/,script-path=https://raw.githubusercontent.com/NobyDa/Script/master/iQIYI-DailyBonus/iQIYI.js

#小米运动获取
小米运动获取Token = type=http-response,pattern=^https:\/\/account\.huami\.com\/v2\/client\/login, requires-body=1, max-size=0, script-path=https://github.com/zhihenglu/SurgeModule/raw/master/Script/xmSports.js

[MITM]
hostname = %APPEND% api.m.jd.com,  wapside.189.cn:9001, *.video.qq.com,ifac*.iqiyi.com,account.huami.com

