#!name=Get cookie
#!desc=该模块适用于定时签到脚本的Cookie获取. 
#!system=ios

[Script]

# 京东
爱奇艺获取Cookie = type=http-request,pattern=^https:\/\/passport\.iqiyi\.com\/apis\/user\/,script-path=https://raw.githubusercontent.com/NobyDa/Script/master/iQIYI-DailyBonus/iQIYI.js

#小米运动获取
小米运动获取Token = type=http-response,pattern=^https:\/\/account\.huami\.com\/v2\/client\/login, requires-body=1, max-size=0, script-path=https://github.com/zhihenglu/SurgeModule/raw/master/Script/xmSports.js

彩云天气 = type=http-request,pattern=https://((weather-data.apple)|(api.weather)).com,script-path=https://raw.githubusercontent.com/Peng-YM/QuanX/master/Tasks/caiyun.js,script-update-interval=0

[MITM]
hostname = %APPEND% ms.jr.jd.com,me-api.jd.com,account.huami.com,weather-data.apple.com,api.weather.com

