#!name=Apple WLOC 
#!desc=Apple WLOC

[Script]


Apple WLOC = type=http-response, pattern="^https?:\/\/gs-loc(-cn)?\.apple\.com\/clls\/wloc", requires-body=1, binary-body-mode=1, max-size=0, timeout=30, script-path=https://github.com/zhihenglu/SurgeModule/raw/refs/heads/master/Script/vloc.js, argument=longitude=113.94114&latitude=22.544577&accuracy=25&logLevel=info


WLOC Settings = type=http-request, pattern="^https?:\/\/gs-loc(-cn)?\.apple\.com\/wloc-settings\/save", requires-body=0, max-size=0, timeout=10, script-path=https://github.com/zhihenglu/SurgeModule/raw/refs/heads/master/Script/vloc.js